version: '3'

services:

  #  postgres:
  #    image: postgres
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_DB: keycloak
  #      POSTGRES_USER: keycloak
  #      POSTGRES_PASSWORD: password

  keycloak:
    build: ./keycloak
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  neo4j:
    build: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
